version: "3.8"
services:
  backend-feed:
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
    image: yourrealusername/udagram-api-feed:v1

  backend-user:
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
    image: yourrealusername/udagram-api-user:v1

  reverseproxy:
    build:
      context: ./udagram-reverseproxy
      dockerfile: Dockerfile
    image: yourrealusername/reverseproxy:v1

  frontend:
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
    image: yourrealusername/udagram-frontend:v1
